import { StyleSheet, Platform, Dimensions, StatusBar } from 'react-native';

const { width: SCREEN_W, height: SCREEN_H } = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#13131f' },
  verifyModalContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 20 },
  verifyModalContent: {
    width: '100%',
    maxWidth: 380,
    backgroundColor: 'rgba(23, 23, 37, 0.98)',
    borderRadius: 32,
    padding: 30,
    alignItems: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.15)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.6,
    shadowRadius: 40,
    elevation: 25,
  },
  verifyIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 24,
    backgroundColor: 'rgba(91, 95, 239, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(91, 95, 239, 0.3)',
  },
  verifyTitle: { 
    color: '#fff', 
    fontSize: 26, 
    fontWeight: '900', 
    marginBottom: 10,
    letterSpacing: -0.5
  },
  verifyDesc: { 
    color: 'rgba(255, 255, 255, 0.5)', 
    fontSize: 14, 
    textAlign: 'center', 
    lineHeight: 22, 
    marginBottom: 32,
    paddingHorizontal: 10
  },
  verifyInput: {
    width: '100%',
    height: 64,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    color: '#fff',
    fontSize: 32,
    fontWeight: '800',
    textAlign: 'center',
    letterSpacing: 12,
    marginBottom: 12,
  },
  verifyActions: { 
    flexDirection: 'row', 
    gap: 12, 
    width: '100%',
    marginTop: 10
  },
  verifyCancelBtn: { 
    flex: 1, 
    height: 54, 
    justifyContent: 'center', 
    alignItems: 'center', 
    borderRadius: 18, 
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.1)'
  },
  verifyCancelText: { 
    color: 'rgba(255, 255, 255, 0.6)', 
    fontWeight: '700',
    fontSize: 15
  },
  verifyConfirmBtn: { 
    flex: 2, 
    height: 54, 
    justifyContent: 'center', 
    alignItems: 'center', 
    borderRadius: 18, 
    backgroundColor: '#5B5FEF',
    shadowColor: '#5B5FEF',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 15,
    elevation: 10
  },
  verifyConfirmText: { 
    color: '#fff', 
    fontWeight: '900',
    fontSize: 16,
    letterSpacing: 0.5
  },

  headerTitle: { color: '#fff', fontSize: 22, fontWeight: '800' },

  scroll: {
    paddingTop: Platform.OS === 'ios' ? 100 : 90, // Push content below the global top bar logo
    paddingHorizontal: 16,
    paddingBottom: 160, // Standardize bottom padding to allow content to enter navigation area
  },

  // ── Profile card
  profileCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    marginBottom: 20,
    overflow: 'hidden',
  },
  profileCardInner: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: 20,
    minHeight: 120,
  },
  profileGradient: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 20,
  },
  avatarRing: {
    position: 'absolute',
    top: 8,
    left: 8,
    width: 64, height: 64,
    borderRadius: 32,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    padding: 3,
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  avatar: {
    width: '100%',
    height: '100%',
    borderRadius: 28,
  },
  profileInfo: { flex: 1, gap: 2 },
  profileName: { color: '#fff', fontSize: 18, fontWeight: '800' },
  profileEmail: { color: '#cbd5e1', fontSize: 13 },
  profileBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    alignSelf: 'center',
    borderWidth: StyleSheet.hairlineWidth,
  },
  profileBadgeText: { 
    color: '#f59e0b', 
    fontSize: 11.5, 
    fontWeight: '800', 
    letterSpacing: 0.3,
    textTransform: 'uppercase'
  },
  editBtn: {
    position: 'absolute',
    top: 10,
    right: 10,
    padding: 6,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 10,
    overflow: 'hidden',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    zIndex: 10,
  },

  // ── Stats
  statsRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 24,
  },
  statCard: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    overflow: 'hidden',
  },
  statCardInner: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 18,
    gap: 4,
  },
  statValue: { color: '#fff', fontSize: 20, fontWeight: '900', letterSpacing: -0.5 },
  statLabel: { color: '#94a3b8', fontSize: 11, fontWeight: '700', marginTop: 2 },

  // ── Menu section
  sectionLabel: {
    color: '#cbd5e1',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 10,
    marginLeft: 4,
  },
  menuSection: {
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    marginBottom: 24,
    overflow: 'hidden',
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  menuRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    gap: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255,255,255,0.06)',
  },
  menuIcon: {
    width: 38, height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuTextWrap: { flex: 1, gap: 1 },
  menuTitle: { color: '#fff', fontSize: 15, fontWeight: '600' },
  menuSub: { color: '#cbd5e1', fontSize: 11 },

  // ── Logout
  logoutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    paddingVertical: 14,
    width: '60%',
    alignSelf: 'center',
    borderRadius: 25,
    backgroundColor: 'rgba(239, 68, 68, 0.05)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(239, 68, 68, 0.35)',
    marginBottom: 40,
    overflow: 'hidden',
    shadowColor: '#ef4444',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  logoutText: { color: '#ef4444', fontSize: 16, fontWeight: '900', letterSpacing: 0.5 },

  // ── Footer
  versionText: {
    textAlign: 'center',
    color: '#cbd5e1',
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 1.5,
  },
  // ── About Modal Styles (now using settings modal styles)
  settingsModalContainer: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  settingsModalContent: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: Platform.OS === 'ios' ? 50 : 40,
  },
  settingsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255,255,255,0.12)',
    marginBottom: 16,
  },
  settingsModalTitle: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '800',
    flex: 1,
    marginLeft: 12,
  },
  aboutSection: {
    marginBottom: 16,
  },
  aboutLabel: {
    color: '#94a3b8',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 4,
  },
  aboutValue: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  aboutDesc: {
    color: '#cbd5e1',
    fontSize: 13,
    lineHeight: 20,
    marginBottom: 4,
  },
  aboutDescSmall: {
    color: '#94a3b8',
    fontSize: 11,
    lineHeight: 16,
    marginTop: 8,
  },
  featureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  featureText: {
    color: '#cbd5e1',
    fontSize: 13,
    fontWeight: '500',
  },
  contactItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(255,255,255,0.03)',
    padding: 10,
    borderRadius: 10,
    marginBottom: 6,
  },
  infoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  infoLabel: {
    color: '#94a3b8',
    fontSize: 13,
  },
  infoValue: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '600',
  },
  legalLinks: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginBottom: 4,
  },
  legalLink: {
    color: '#818cf8',
    fontSize: 12,
    fontWeight: '600',
  },
  legalDivider: {
    width: 1,
    height: 12,
    backgroundColor: 'rgba(0,0,0,0.1)',
  },
  updateCheckCard: {
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderRadius: 16,
    padding: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
  },
  updateStatusContainer: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(255,255,255,0.12)',
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    justifyContent: 'center',
  },
  statusText: {
    color: '#818cf8',
    fontSize: 12,
    fontWeight: '600',
  },
  // ── Full-Screen Modal Styles (now using settings modal styles)
  fullScreenCloseBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.05)',
    alignItems: 'center',
    justifyContent: 'center',
  },

  settingsIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsScroll: {
    flex: 1,
  },
  settingsContentSection: {
    gap: 16,
  },
  settingsText: {
    color: '#94a3b8',
    fontSize: 14,
    lineHeight: 22,
  },
  settingsList: {
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
  },
  settingsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    paddingHorizontal: 22,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255,255,255,0.08)',
  },
  settingsRowText: {
    color: '#e2e8f0',
    fontSize: 15,
    fontWeight: '600',
  },
  // ── Notification Styles
  notificationCard: {
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
  },
  notificationIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notifTitle: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  notifTime: {
    color: 'rgba(255,255,255,0.3)',
    fontSize: 11,
  },
  notifMessage: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: 13,
    marginTop: 2,
    lineHeight: 18,
  },
  unreadDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#6366f1',
    marginLeft: 4,
  },

  backBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 16,
    backgroundColor: 'rgba(129,140,248,0.1)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    alignSelf: 'flex-start',
  },
  backBtnText: {
    color: '#818cf8',
    fontSize: 13,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  pillBack: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 50,
    overflow: 'hidden',
    backgroundColor: '#5B5FEF',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.3)',
    shadowColor: '#5B5FEF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.45,
    shadowRadius: 10,
    elevation: 8,
    marginBottom: 20,
    alignSelf: 'flex-start',
  },
  pillLabel: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  pillSheen: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '50%',
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderRadius: 50,
  },
  // ── Glass Subscription Styles
  coverageBlur: {
    marginBottom: 20,
    borderRadius: 20,
    overflow: 'hidden',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
  },
  coverageGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  coverageContent: {
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  coverageLabel: {
    color: '#10b981',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  coverageValue: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '900',
  },
  glassSubscriptionCard: {
    borderRadius: 24,
    overflow: 'hidden',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
  },
  cardDivider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.03)',
    marginVertical: 12,
  },
  benefitTag: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
  },
  benefitTagText: {
    color: '#cbd5e1',
    fontSize: 12,
    fontWeight: '600',
  },
  detailCard: {
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderRadius: 20,
    padding: 16,
    gap: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
  },
  detailRow: {
    gap: 4,
  },
  detailLabel: {
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  detailValue: {
    color: '#f1f5f9',
    fontSize: 16,
    fontWeight: '600',
  },
  editInput: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    padding: 10,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    marginTop: 4,
  },
  passInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    marginTop: 4,
  },
  passInput: {
    flex: 1,
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    padding: 10,
  },
  passEye: {
    paddingHorizontal: 12,
  },
  editActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 20,
  },
  editActionBtn: {
    flex: 1,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveBtn: {
    backgroundColor: '#5B5FEF',
  },
  cancelBtn: {
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.22)',
  },
  mainEditBtn: {
    flex: 1,
    height: 48,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.22)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  editActionText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  // ── Analytics Styles
  analyticsMain: {
    alignItems: 'center',
    paddingVertical: 32,
    backgroundColor: 'rgba(129,140,248,0.08)',
    borderRadius: 32,
    marginBottom: 24,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.22)',
    overflow: 'hidden',
  },
  analyticsTotal: {
    color: '#fff',
    fontSize: 56,
    fontWeight: '900',
    letterSpacing: -1,
  },
  analyticsSub: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 2,
    marginTop: 4,
  },

  genreRow: {
    marginBottom: 20,
  },
  genreInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  genreName: {
    color: '#e2e8f0',
    fontSize: 15,
    fontWeight: '600',
  },
  genreValue: {
    color: '#818cf8',
    fontSize: 14,
    fontWeight: '700',
  },
  progressBg: {
    height: 8,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#5B5FEF',
    borderRadius: 4,
  },
  // ── Usage Analytics
  usageRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 24,
  },
  usageCard: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderRadius: 24,
    padding: 20,
    alignItems: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.22)',
  },
  usageLabel: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 6,
  },
  usageValue: {
    color: '#fff',
    fontSize: 24,
    fontWeight: '800',
  },

  activityChart: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    height: 140,
    backgroundColor: 'rgba(255,255,255,0.02)',
    borderRadius: 24,
    padding: 20,
    marginBottom: 24,
  },
  chartCol: {
    alignItems: 'center',
    flex: 1,
  },
  barBg: {
    width: 6,
    height: 80,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 3,
    justifyContent: 'flex-end',
    marginBottom: 8,
  },
  barFill: {
    width: '100%',
    borderRadius: 8,
    overflow: 'hidden',
    justifyContent: 'flex-start',
  },
  barSheen: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '40%',
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 8,
  },
  chartDay: {
    color: 'rgba(255,255,255,0.3)',
    fontSize: 10,
    fontWeight: '700',
    marginTop: 10,
  },
  // ── Storage Card
  storageCard: {
    backgroundColor: 'rgba(16,185,129,0.08)',
    borderRadius: 24,
    padding: 20,
    marginBottom: 32,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(16,185,129,0.22)',
  },
  storageInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  storageLabel: {
    color: '#10b981',
    fontSize: 14,
    fontWeight: '700',
  },
  storageValue: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  // ── Download Items
  downloadCard: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 12,
    marginBottom: 12,
    overflow: 'hidden',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
  },
  downloadPosterContainer: {
    width: 100,
    height: 140,
  },
  downloadPoster: {
    width: '100%',
    height: '100%',
  },
  downloadInfo: {
    flex: 1,
    padding: 12,
    justifyContent: 'center',
  },
  downloadTitle: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 4,
  },
  downloadMeta: {
    color: 'rgba(255, 255, 255, 0.5)',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 12,
  },
  downloadActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  downloadPlayBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#5B5FEF',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  downloadPlayText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
  },
  downloadDeleteBtn: {
    padding: 6,
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
    borderRadius: 8,
  },
  // ── Grid Card (My List)
  gridCard: {
    width: (SCREEN_W - 44) / 3,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 12,
    marginBottom: 12,
    overflow: 'hidden',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
  },
  gridPoster: {
    width: '100%',
    height: 150,
    resizeMode: 'cover',
  },
  gridInfo: {
    padding: 6,
    alignItems: 'center',
  },
  gridTitle: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 2,
  },
  gridMeta: {
    color: 'rgba(255, 255, 255, 0.4)',
    fontSize: 9,
    fontWeight: '600',
    textAlign: 'center',
  },
  // ── Badges Small
  vjBadgeSmall: {
    position: 'absolute',
    top: 6,
    left: 6,
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
  },
  vjBadgeTextSmall: {
    color: '#fff',
    fontSize: 8,
    fontWeight: '800',
  },
  genreBadgeSmall: {
    position: 'absolute',
    bottom: 6,
    left: 6,
    backgroundColor: 'rgba(0,0,0,0.7)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
  },
  genreBadgeTextSmall: {
    color: '#fff',
    fontSize: 8,
    fontWeight: '800',
  },
  // ── Watchlist Grid
  watchlistGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    justifyContent: 'flex-start',
    marginTop: 16,
    paddingHorizontal: 0,
  },
  // ── Deletion Styles
  deletionWarningBox: {
    backgroundColor: 'rgba(245,158,11,0.05)',
    borderRadius: 24,
    padding: 24,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(245, 158, 11, 0.35)',
    marginBottom: 20,
  },
  deletionTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 8,
  },
  deletionDesc: {
    color: '#94a3b8',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 16,
  },
  consequenceList: {
    gap: 12,
  },
  consequenceItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  consequenceText: {
    color: '#cbd5e1',
    fontSize: 13,
    fontWeight: '500',
  },
  confirmToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 16,
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderRadius: 16,
    marginBottom: 24,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxActive: {
    backgroundColor: '#ef4444',
    borderColor: '#ef4444',
  },
  confirmText: {
    color: '#94a3b8',
    fontSize: 13,
    fontWeight: '600',
    flex: 1,
  },
  finalDeleteBtn: {
    height: 56,
    borderRadius: 18,
    backgroundColor: '#ef4444',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#ef4444',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  deleteBtnDisabled: {
    backgroundColor: 'rgba(239,68,68,0.2)',
    opacity: 0.5,
  },
  finalDeleteText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '800',
  },
  emailConfirmSection: {
    marginBottom: 24,
    gap: 8,
  },
  emailConfirmLabel: {
    color: '#94a3b8',
    fontSize: 13,
    fontWeight: '500',
    lineHeight: 18,
  },
  requestCodeBtn: {
    backgroundColor: '#5B5FEF',
    height: 48,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 12,
  },
  requestCodeText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  errorText: {
    color: '#ef4444',
    fontSize: 12,
    fontWeight: '600',
    marginTop: 8,
    textAlign: 'center',
  },
  // ── Security Sub-section Styles
  fullScreenActionBtn: {
    backgroundColor: 'transparent',
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    width: '100%',
    overflow: 'hidden',
  },
  fullScreenActionText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  securityCard: {
    backgroundColor: 'rgba(255,255,255,0.03)',
    borderRadius: 24,
    padding: 24,
    marginTop: 16,
  },
  securityTitle: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 8,
  },
  securityDesc: {
    color: '#94a3b8',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 24,
  },
  sessionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255,255,255,0.12)',
  },
  sessionIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.05)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  sessionInfo: {
    flex: 1,
  },
  sessionDevice: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  sessionDetails: {
    color: '#64748b',
    fontSize: 13,
    marginTop: 4,
    fontWeight: '500',
  },
  currentStatus: {
    color: '#34d399',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  tfaToggleBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    backgroundColor: 'rgba(129,140,248,0.1)',
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(129, 140, 248, 0.4)',
    marginBottom: 24,
  },
  tfaLabel: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  tfaStatus: {
    color: '#818cf8',
    fontSize: 14,
    fontWeight: '800',
  },
  successBanner: {
    backgroundColor: 'rgba(52,211,153,0.1)',
    padding: 16,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 20,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(52, 211, 153, 0.4)',
  },
  successText: {
    color: '#34d399',
    fontSize: 14,
    fontWeight: '700',
  },
  // ── Profile Photo Edit Styles
  changePhotoSection: {
    alignItems: 'center',
    marginBottom: 24,
    marginTop: 8,
  },
  editAvatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(129,140,248,0.3)',
  },
  changePhotoBadge: {
    position: 'absolute',
    bottom: -8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 24,
    alignSelf: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    shadowColor: '#3d44ff',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 5,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(255,255,255,0.3)',
    overflow: 'hidden',
  },
  changePhotoText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  avatarCameraOverlay: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#5B5FEF',
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#111827',
  },
  socialLinkBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
    padding: 16,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    gap: 12,
  },
  socialLinkText: {
    flex: 1,
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  linkStatus: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  // ── Glass Redesign Styles
  glassCardWrap: {
    borderRadius: 32,
    overflow: 'hidden',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
  },
  glassCard: {
    padding: 24,
    backgroundColor: 'rgba(255,255,255,0.03)',
  },
  glassAvatarRing: {
    width: 110,
    height: 110,
    borderRadius: 55,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(129,140,248,0.5)',
    padding: 4,
    alignSelf: 'center',
    marginBottom: 20,
  },
  detailsListGlass: {
    gap: 16,
  },
  glassDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: 'rgba(255,255,255,0.05)',
  },
  glassDetailIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.05)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  glassDetailLabel: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 4,
  },
  glassDetailValue: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  glassEditInput: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    padding: 0,
    height: 24,
  },
  glassMainEditBtn: {
    height: 52,
    borderRadius: 50,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    overflow: 'hidden',
    // Removed heavy indigo shadow to match hero button's more subtle look
  },
  glassSaveBtn: {
    height: 52,
    backgroundColor: '#5B5FEF', // Standardized Design 2
    borderRadius: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    shadowColor: '#5B5FEF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.45,
    shadowRadius: 10,
    elevation: 8,
    overflow: 'hidden',
  },
  glassCancelBtn: {
    height: 52,
    backgroundColor: 'rgba(255, 255, 255, 0.05)', // Design 3
    borderRadius: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
  },
  glassActionText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '800',
  },
  header: {
    paddingHorizontal: 20,
    paddingTop: 20,
    marginBottom: 20,
    gap: 8,
  },
  sectionHeaderBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 50,
    overflow: 'hidden',
    backgroundColor: '#5B5FEF',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    shadowColor: '#5B5FEF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
  },
  rowTitle: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  headerSub: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: 12,
    fontWeight: '600',
    paddingHorizontal: 4,
  },
  headerLeadingWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
    flex: 1,
  },
  headerLeadingIcon: {
    width: 48,
    height: 48,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    overflow: 'hidden',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
  },
  circularCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.05)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
  },
  capsuleDoneBtn: {
    backgroundColor: 'rgba(91, 95, 239, 0.25)',
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    shadowColor: '#5B5FEF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.45,
    shadowRadius: 10,
    elevation: 8,
    width: '100%',
    overflow: 'hidden',
  },
  modalFooter: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    paddingBottom: Platform.OS === 'ios' ? 44 : 24,
    paddingTop: 60,
  },
  footerGradient: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: Platform.OS === 'ios' ? 110 : 90,
  },
  capsuleDoneText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  menuSectionHeader: {
    marginBottom: 12,
    marginTop: 8,
    paddingHorizontal: 4,
  },
  historyCard: {
    borderRadius: 24,
    overflow: 'hidden',
    marginBottom: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
  },
  // ── Redesigned Personal Info Styles
  compactProfileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderRadius: 24,
    padding: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    marginBottom: 20,
  },
  compactAvatarWrapper: {
    width: 68,
    height: 68,
    borderRadius: 34,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#818cf8',
    padding: 2,
  },
  compactAvatar: {
    width: '100%',
    height: '100%',
    borderRadius: 32,
  },
  avatarMiniBadge: {
    position: 'absolute',
    bottom: -2,
    right: -2,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#5B5FEF',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#0f0f14',
  },
  headerInfo: {
    flex: 1,
  },
  headerDisplayName: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 2,
  },
  headerEmail: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: 13,
    fontWeight: '600',
  },
  piInfoCardGroup: {
    marginBottom: 20,
  },
  piInfoGroupTitle: {
    color: 'rgba(255,255,255,0.3)',
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginBottom: 10,
    marginLeft: 4,
  },
  piInfoCard: {
    borderRadius: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    overflow: 'hidden',
  },
  piInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 18,
    paddingHorizontal: 16,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(255,255,255,0.1)',
  },
  piNoBorder: {
    borderTopWidth: 0,
  },
  piInfoIcon: {
    width: 24,
    marginRight: 12,
  },
  piInfoLabel: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 2,
  },
  piInfoValue: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  piInfoInput: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.15)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginTop: 6,
    height: 44,
  },
  piInfoInputFocused: {
    borderColor: '#818cf8',
    backgroundColor: 'rgba(129, 140, 248, 0.08)',
  },
  piNameGrid: {
    flexDirection: 'row',
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(255,255,255,0.1)',
  },
  piGridItem: {
    flex: 1,
    padding: 16,
    borderRightWidth: StyleSheet.hairlineWidth,
    borderRightColor: 'rgba(255,255,255,0.1)',
  },
  piMetadataPill: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 50,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    height: 44,
  },
  piMetadataText: {
    color: 'rgba(255,255,255,0.4)',
    fontSize: 11,
    fontWeight: '700',
  },
  piMainEditBtnWrapper: {
    alignSelf: 'stretch',
  },

  piMainEditBtn: {
    height: 44,
    borderRadius: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    overflow: 'hidden',
  },
  piMainEditBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
  piEditActionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginTop: 20,
    paddingHorizontal: 20,
  },
  piCancelBtn: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 50,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
  },
  piCancelBtnText: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 14,
    fontWeight: '700',
  },
  piSaveBtnWrapper: {
    flex: 1,
    maxWidth: 200,
  },
  piSaveBtn: {
    height: 46,
    backgroundColor: '#5B5FEF',
    borderRadius: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.3)',
    shadowColor: '#5B5FEF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.45,
    shadowRadius: 10,
    elevation: 8,
    overflow: 'hidden',
  },
  piSaveBtnText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '800',
  },
  socialRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 12,
    marginTop: 10,
    marginBottom: 24,
    paddingHorizontal: 2,
  },
  socialIconBtn: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255, 255, 255, 0.22)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    overflow: 'hidden',
  },
  websiteRow: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: 'rgba(255,255,255,0.12)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  websiteText: {
    color: '#38bdf8',
    fontSize: 12,
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
});
